---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    dhcpd_subnets:
      - subnet: "{{ ansible_default_ipv4.network }}/ansible_default_ipv4.subnet"
        parameters:
          interface: "{{ ansible_default_ipv4.interface }}"

  roles:
    - role: ansible-role-dhcpd
